# Generated by Django 3.0.5 on 2020-04-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200430_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='gst_no',
            new_name='Gst_no',
        ),
    ]
