# Generated by Django 3.0.5 on 2020-04-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='contact',
            new_name='Email_Id',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='email',
            new_name='contact_no',
        ),
    ]
