# Generated by Django 3.0.5 on 2020-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='rate',
            field=models.CharField(max_length=200),
        ),
    ]
